# Shell variables
# Generated by 'wal'
wallpaper='/home/emiemiemi/.config/wallpaper.png'

# Special
background='#121213'
foreground='#c2a6b8'
cursor='#c2a6b8'

# Colors
color0='#121213'
color1='#813768'
color2='#89403b'
color3='#97414e'
color4='#a04476'
color5='#b34f5b'
color6='#c16e70'
color7='#c2a6b8'
color8='#877480'
color9='#813768'
color10='#89403b'
color11='#97414e'
color12='#a04476'
color13='#b34f5b'
color14='#c16e70'
color15='#c2a6b8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
