--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/emiemiemi/.config/wallpaper.png"

-- Special
background="#121213"
foreground="#c2a6b8"
cursor="#c2a6b8"

-- Colors
color0="#121213"
color1="#813768"
color2="#89403b"
color3="#97414e"
color4="#a04476"
color5="#b34f5b"
color6="#c16e70"
color7="#c2a6b8"
color8="#877480"
color9="#813768"
color10="#89403b"
color11="#97414e"
color12="#a04476"
color13="#b34f5b"
color14="#c16e70"
color15="#c2a6b8"
